name: check, build, release topdf
run-name: big dog hog to ${{ inputs.deploy_target }} by @${{ github.actor }}

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  haskell_build:
    name: check that it builds
    strategy:
      matrix:
        os: [ubuntu-24.04]
    runs-on: ubuntu-24.04
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      # Nix-specific logic begins here
      - name: build haskell executable
        run: nix build .

  build_and_test_nix:
    name: build flatpak appimage
    needs: haskell_build
    strategy:
      matrix:
        os: [ubuntu-24.04]
    runs-on: ubuntu-24.04
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: some cache jive
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: build package
        run: nix build .
      - name: Build flatpak
        run: nix bundle --bundler github:ralismark/nix-appimage .
