name: release
run-name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_and_test_nix:
    name: build flatpak appimage
    strategy:
      matrix:
        os: [ubuntu-24.04]
    runs-on: ubuntu-24.04
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: build default package
        run: nix build .
      - name: Build flatpak
        run: nix bundle --bundler github:ralismark/nix-appimage .
      - name: Create Github release
        id: create-new-release
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: ${{ github.run_number }}
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./topdf.AppImage
          asset_name: site-v${{ github.run_number }}.zip
          asset_content_type: application/zip
